set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [ get_ports clk ]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [ get_ports reset ]

# led
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {led[15]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {led[8]}]

set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {led[7]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {led[0]}]

# seg
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [ get_ports seg[11] ]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [ get_ports seg[10] ]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [ get_ports seg[9] ]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [ get_ports seg[8] ]

set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [ get_ports seg[7] ]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [ get_ports seg[6] ]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [ get_ports seg[5] ]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [ get_ports seg[4] ]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [ get_ports seg[3] ]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [ get_ports seg[2] ]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [ get_ports seg[1] ]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [ get_ports seg[0] ]